# Generated by Django 6.0.5 on 2026-05-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='customer_name',
            field=models.CharField(default='Walk_in Customer', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={},
        ),
        migrations.AddField(
            model_name='sales',
            name='customer_type',
            field=models.CharField(choices=[('wholesale', 'Wholesale'), ('retail', 'Retail'), ('walk_in', 'Walk_in')], default=' retail', max_length=20),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
