# Generated by Django 6.0.5 on 2026-05-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0002_alter_sales_customer_name_alter_sales_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='transport_required',
            field=models.BooleanField(default=False),
        ),
    ]
