# Generated by Django 6.0.5 on 2026-05-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='amount_due',
            field=models.IntegerField(default=0),
        ),
    ]
